### ISSUE TITLE
problem with carnet_login

### ISSUE THREAD

**Issue by aagudeloz** [mikaelho/youey#2]
I have problems running the app. I search in internet and test two programs, nothing. can you help me? Where I download the correct program. 

Thanks a lot

**Comment by mikaelho** [comment]
What are you trying to do?

**Comment by aagudeloz** [comment]
I'm trying youey and I've tried to run dashboard.py (this is where I have problems); I can not find carnet_login, I have tried several scripts. Can you tell me what to do to prove it?

Another question, can I use WKWebView with flask to not use Safari?

Thanks a lot

**Comment by mikaelho** [comment]
Ok. Dashboard.py is very much unfinished and broken. In any case you would need your personal login information to your own car to try it out. BUT I just committed a version that uses dummy data.

For your other question: yes, you can use WKWebView as a browser. Depending on your use case, you might want to implement some extra things like back/forward buttons.
